### PR TITLE
Added Footer and also made the website responsive

### PR DESCRIPTION
**Pull request by suraj-9849**
Issue : #5

### CODE REVIEW

**Comment by suraj-9849** [comment]
@nikhilbhatia08 
This pull request includes several updates to the `DataBaseHome`, `DbEnter`, `Navbar`, and `SelectDs` components, as well as the addition of a new `Footer` component. The changes primarily focus on improving the user interface and responsiveness of the application.

**Comment by nikhilbhatia08** [comment]
@suraj-9849 can I know what is lucid React ?

**Comment by suraj-9849** [comment]
> @suraj-9849 can I know what is lucid React ?
        Show icons dynamically by icon name. (React icons library)

**Comment by suraj-9849** [comment]
show icons dynamically by icon name. (React-icon library)

**Comment by nikhilbhatia08** [comment]
@suraj-9849 Yes please remove it, for icons we can use react hero icons

**Comment by nikhilbhatia08** [comment]
@suraj-9849 Thanks for your contribution.

**Pull request merged**
